# Generated by Django 5.2.8 on 2025-12-16 19:28

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import paradedb.indexes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=500)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("category", models.CharField(max_length=100)),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("actual_price", models.IntegerField()),
                ("selling_price", models.IntegerField()),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=6
                    ),
                ),
                ("average_rating", models.IntegerField(blank=True, default=0)),
                ("out_of_stock", models.BooleanField(blank=True, default=False)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=500),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("product_details", models.JSONField(default=list)),
                ("created", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="UserProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_product",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("rank", models.IntegerField(default=0)),
                ("published", models.BooleanField(default=True)),
                (
                    "price_range",
                    django.contrib.postgres.fields.ranges.IntegerRangeField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "date_range",
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        blank=True, default=None, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "article",
                "indexes": [
                    paradedb.indexes.Bm25Index(
                        models.F("id"),
                        models.F("title"),
                        models.F("description"),
                        models.F("rank"),
                        models.F("published"),
                        models.F("price_range"),
                        models.F("date_range"),
                        models.F("created"),
                        models.F("user"),
                        paradedb.indexes.IndexField(
                            models.F("tags"), tokenizer_cast="pdb.ngram(1,2)"
                        ),
                        models.F("metadata"),
                        fields_config=paradedb.indexes.IndexFieldConfig(
                            json_fields=[
                                paradedb.indexes.JSONFieldIndexConfig(
                                    "metadata", fast=True
                                )
                            ]
                        ),
                        key_field="id",
                        name="article_bm25_idx",
                        with_extra=None,
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=paradedb.indexes.Bm25Index(
                models.F("id"),
                models.F("title"),
                paradedb.indexes.IndexField("brand", "pdb.literal"),
                models.F("description"),
                paradedb.indexes.IndexField("category", "pdb.literal"),
                paradedb.indexes.IndexField("sub_category", "pdb.simple"),
                models.F("selling_price"),
                models.F("average_rating"),
                models.F("out_of_stock"),
                paradedb.indexes.IndexField("product_details", "pdb.literal"),
                models.F("created"),
                models.F("user"),
                fields_config=None,
                key_field="id",
                name="product_bm25_idx",
                with_extra=None,
            ),
        ),
        migrations.AddIndex(
            model_name="userproduct",
            index=paradedb.indexes.Bm25Index(
                models.F("id"),
                models.F("user"),
                models.F("product"),
                fields_config=None,
                key_field="id",
                name="user_product_bm25_idx",
                with_extra=None,
            ),
        ),
    ]
